version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:12.6-browsers
    steps:
      - checkout
      - restore_cache:
          key: v2-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: v2-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/.cache
            - ./node_modules
      - run: yarn test
      
